[ftr] Provide user separate options to upload sample and project files
ElucidataInc/ElMaven pull request #1323
Opened 2020-07-28 09:52 UTC by sakshikukreja14

Now two separate options are provided to user to upload sample and project files. Moreover, user would be notified if he tries to open project file in upload sample file option.
secondly, user would be notified if he tries to open more than one project files at a time.

2020-08-19 07:09 UTC, saifulbkhan commented
@sakshikukreja14 Before I review this, can you tell me why we had to separate the "Open" action into two sub-actions? I dislike the fact that of all the buttons in the main toolbar, we have the "Open" button with a menu - breaks consistency.

This could have been a much simpler fix:
1. Allow the user to select any number and type of files which are now stored in `filelist`.
2. Run through `filelist` to check if there are any conflicting cases, i.e.,
    - if samples and emDB files both were selected
    - if two emDB files we selected
3. If so, then either allow the user to re-chose which files they really want or make a decision to load the first type of file (if sample then only load samples, if emDB then only load the first emDB) in the list.

I have a feeling that the product/design folks will have an issue with your approach as well. But you may still discuss this with Surbhi and chose which implementation we should go with.

2020-08-20 05:30 UTC, sakshikukreja14 commented
@saifulbkhan I have changed the implementation according to what was required. Apologies for misunderstanding requirements.

2020-08-20 23:43 UTC, saifulbkhan requested changes
@sakshikukreja14 Thanks for making the change. Looks much better now. If you resolve the comments and rebase, this will ready to merge.

2020-08-20 23:43 UTC, saifulbkhan commented on src/gui/mzroll/mainwindow.cpp
> +                       "project files on one instance.\n\n"
"It seems you are trying to load sample files and project files at once. Please select either a set of samples or a single project file to load into this session."

2020-08-20 23:43 UTC, saifulbkhan commented on src/gui/mzroll/mainwindow.cpp
> +        msgBox.setDefaultButton(sampleChosen);
I would have made the project button as default. The first project in the file list.

2020-08-20 23:43 UTC, saifulbkhan commented on src/gui/mzroll/mainwindow.cpp
> +    connect(btnOpen, SIGNAL(clicked()), SLOT(open()));
Use the type-strict syntax for connecting signals-slots.

2020-08-20 23:43 UTC, saifulbkhan commented on src/gui/mzroll/mainwindow.h
> +	void showLargeFilesNotification(QStringList, QFileInfo);
This is no longer required, right?

2020-08-21 06:40 UTC, merged